### ISSUE TITLE
Can't run npm run docs

### ISSUE THREAD

**Issue by kennarddh** [mcqua007/quantdom#2]
Error:
```bash
$ npm run docs

> quantdom@1.1.2 docs
> node_modules/.bin/jsdoc2md src/index.js

'node_modules' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by mcqua007** [comment]
Hmm what version node are you running ? My guess is you are no an older version and it needs the relative path. I am running `node version 16.13.2` and `npm version 8.1.2`.

Either way I will try adding seeing if editing the command fixes that for you. As a heads up I am still in pre-release phase and making changes to this repo pretty fast. For example since you posted this I have removed gulp and implemented rollup instead.

**Comment by mcqua007** [comment]
@kennarddh Okay, I added this [change](https://github.com/mcqua007/quantdom/commit/472ee4a04aaee5dd18603182aa1c9d2c498f5b0a). Can you pull down the change and see if that works for you and let me know here ? Also probably a good idea to update node and npm for this directory and re-install your node_modules since I added and removed some packages since you posted this.

**Comment by kennarddh** [comment]
@mcqua007 I am running node version 16.13.0 and npm version 8.1.0.

**Comment by kennarddh** [comment]
@mcqua007 still can't

Error:
```bash
$ npm run docs

> quantdom@1.1.12 docs
> node ./node_modules/.bin/jsdoc2md src/index.js

D:\ken\coding\js\personal\_contribute\quantdom\node_modules\.bin\jsdoc2md:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1031:15)
    at Module._compile (node:internal/modules/cjs/loader:1065:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47
```

**Comment by kennarddh** [comment]
What shell you use? I use bash

**Comment by mcqua007** [comment]
> What shell you use? I use bash

I'm use fish but this works in zsh as well. Are you in mac ?

Also are you running from root of project directory. You can try removing node in front of the relative path or we can try using npx as outlined in my other comment. We need to run these these commands from the project level.

I think the issues is there was a typo in my last fix where I missed a space. I changed the commands to use npx so it should work now.

https://github.com/mcqua007/quantdom/commit/8e803e843bbe9e22fdaefa505bdd916cc04e4d5a

**Comment by kennarddh** [comment]
Im on windows 10

**Comment by kennarddh** [comment]
I use git bash

**Comment by mcqua007** [comment]
`npx jsdoc2md ./src/index.js > docs.md` I made this change this should have fixed your issues based off the other thread.
I am gonna close this issue for now.
