### ISSUE TITLE
Use eslint and prettier

### ISSUE THREAD

**Issue by kennarddh** [mcqua007/quantdom#3]
- [eslint](https://eslint.org/)
- [prettier](https://prettier.io/)

**Comment by mcqua007** [comment]
Sure I will go ahead an add them at the project level. I'll resolve the issue once it is done.

**Comment by mcqua007** [comment]
Added the changes because your PR had some issues with unclean commits and there was errors in your code as well. I really appreciate your help and I think this was a great proposal. Good job on all the testing changes. For future changes you can target master as using staging is too cumbersome and made the commit history a little messy.

Here are the changes for reference:

eslint - https://github.com/mcqua007/quantdom/pull/15 & prettier - b32c2368f5a11a1ee728b7024a640cf05fecc327
